# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
    - name: Make directory for asdf systems
      run: |
        mkdir ~/common-lisp
        rm -rf ~/work/cl-fasta-to-notes/cl-fasta-notes/build
        cp -r ~/work/cl-fasta-to-notes/cl-fasta-notes ~/common-lisp
    
    - name: Install SBCL
      run: sudo apt install sbcl
    
    - name: Install asdf
      run: sudo apt install cl-asdf
    
    - name: Install quicklisp
      run: |
        sudo apt install cl-quicklisp
        sbcl --non-interactive --load '/usr/share/common-lisp/source/quicklisp/quicklisp.lisp' --eval '(quicklisp-quickstart:install)'
    - name: Build binary
      run: sbcl --non-interactive --eval '(require "asdf")' --eval '#-quicklisp (let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))) (when (probe-file quicklisp-init) (load quicklisp-init)))' --eval '(ql:quickload :fasta-notes)' --eval '(asdf:operate :build-op :fasta-notes)'
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ~/common-lisp/cl-fasta-notes/build/fasta-notes
